version: '3.5'

services:
  dev:
    hostname: request
    extends:
      file: docker-compose.common.yml
      service: request_base
    build:
      target: dev # NOTE: this is the "stage" in the Dockerfile
      context: .
    profiles:
      - dev
    ports:
      - '9004:9004'
  
  production:
    hostname: request
    extends:
      file: docker-compose.common.yml
      service: request_base
    build:
      target: production # NOTE: this is the "stage" in the Dockerfile
      context: .
    profiles:
      - production
    ports:
      - '9004:9004'

networks:
  hubble-network:
    name: hubble-network
