version: '3.5'
services:
  request:
    container_name: ${PROJECT_NAME?'Please set the ’PROJECT_NAME’ env var before runing docker-compose'}
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - NODE_ENV=development
    volumes:
      - .:/src:delegated
      - /src/node_modules/
      - ~/.gitconfig:/root/.gitconfig:ro

    ports:
      - '9004:9004'
    networks:
      - default
      - hubble-network
networks:
  hubble-network:
    external:
      name: hubble-network
