version: '3.5'

services:
  request:
    hostname: request
    extends:
      file: docker-compose.common.yml
      service: request_base
    build:
      target: dev
      context: .
    ports:
      - '9004:9004'

networks:
  hubble-network:
    name: hubble-network
