version: 2

# build job parameters as a template
defaults: &defaults
  working_directory: ~/repo
  docker:
    # the Docker image with Cypress dependencies
    - image: circleci/node:12
      environment:
        ## this enables colors in the output
        TERM: xterm

default_cache_keys: &default_cache_keys
  keys:
    - v1-yarn-deps-{{ checksum "yarn.lock" }}
    - v1-yarn-deps

default_save_cache: &default_save_cache
  key: v1-yarn-deps-{{ checksum "yarn.lock" }}
  paths:
    - node_modules

install_yarn: &install_yarn
  name: Install yarn
  command: yarn policies set-version 1.x

jobs:
  install_packages:
    # Main build process
    <<: *defaults
    steps:
      # Checkout repo
      - checkout
      - run: *install_yarn
      # Restore yarn cache
      - restore_cache: *default_cache_keys
      # Install & Build
      - run: yarn install
      # Save updated yarn cache
      - save_cache: *default_save_cache

  build:
    <<: *defaults
    steps:
      # Checkout repo
      - checkout
      - run: *install_yarn
      # Restore yarn cache
      - restore_cache: *default_cache_keys
      # Create a build
      - run:
          name: Creating a build
          command: yarn run build
      # Save public repo to a shared workspace
      # This way can be used in future tests
      - persist_to_workspace:
          root: ~/repo/dist
          paths:
            - ./*

  unitTests:
    # Unit tests (jest)
    <<: *defaults
    parallelism: 3
    steps:
      # Checkout git repo
      - checkout
      - run: *install_yarn
      # Restore yarn cache
      - restore_cache: *default_cache_keys
      # Run the jest tests
      - run:
          name: Run tests
          command: |
            yarn test --ci --runInBand
          environment:
            JEST_JUNIT_OUTPUT_DIR: 'reports/junit/js-test-results.xml'
      - store_test_results:
          name: Store test results
          path: ./reports/junit

  linting:
    # Linting (eslint/prettier)
    <<: *defaults
    steps:
      # Checkout git repo
      - checkout
      - run: *install_yarn
      # Restore yarn cache
      - restore_cache: *default_cache_keys
      # Run eslint
      - run:
          name: Running lint processes
          command: yarn lint

workflows:
  version: 2
  build_and_test:
    jobs:
      - install_packages
      - build:
          requires:
            - install_packages
      - unitTests:
          requires:
            - install_packages
      - linting:
          requires:
            - install_packages
