name: Email on merge

on:
  pull_request:
    # Only run when a PR is closed. (There's a check later to ensure this PR is
    # closed and merged, rather than closed and discarded)
    types:
      - closed
    # Limit to PRs that are targeting the main branch
    branches:
      - main

jobs:
  send-email:
    runs-on: ubuntu-latest
    # Only run on merge
    # PRs (hubble-eng-bot)
    if: github.event.pull_request.merged == true
    steps:
      - name: Send changelog email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          # Uses Google credentials for the Hubble service account
          # (eng-bot@hubblehq.com)
          username: ${{ secrets.ENG_BOT_USERNAME }}
          password: ${{ secrets.ENG_BOT_PASSWORD }}
          from: Hubble Engineering Bot 🤖
          to: changelog@hubblehq.com
          subject: '[${{ github.event.repository.full_name }}] ${{ github.event.pull_request.title }}'
          html_body: |
            ${{ github.event.pull_request.body }}<br />
            <br />
            PR: ${{ github.event.pull_request.html_url }}<br />
            Merged by: ${{ github.actor }}
          # GitHub PRs use markdown; parse it here, too.
          convert_markdown: true
